# File managed by pluginsync
sudo: false
language: go
go:
- 1.6.3
- 1.7.1
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: cTZkeCgNSBdKGKfNV1v1bZauUKazTaBpZSHlKFojaDqy4IRbr2mlUQPxGgE4MfABomHmUsm1gq1BkINEZYIj67l+7mir7tegGR/16FXRidzNRRpqaVcVNVuLNxwcP31TK6cH/JFGEC212XMhaWj7+w068yj11B2y/C7x8xuJZG+7+wyFBmN7JqMW0ABxlxY60hB19GQOFb6lOeDRWJdF9iwatWQ67BXzAMCCdKMksR43WX0kDNZ6909xHiz8odWcD1qNxdfZqbazpf8bFBu5Xo88vWC17DXWgVPykveQxQexyZ4DJQ8wY++UOCoobpR8jvXkHwf0q4hYERsGO6JpCc0LRk38ggfoyMt1TBvEtU7JQyRz8WvSDNeGBmtqKDpFjxMbHmp96Ypn6//Y4k5KKg/zxhDTrbzkF25LDfGwv1o4T53b2JA5HIZMoniYX6/awRgN7cmIsD4+5pZFt2ysJbNliJYgf6Bh42FMrySx6cgPyIxXQiinzI7dFQdwTN86GHkPr6D0q/ZFTCgrrGWz2o9yniK/ICPB54JAA5Z9qq+D4YPAD0+daegulheiQWpu2/YatuTH359KwQoKjkAg/XmLZh/eG71nKlsN9DwK3bHOmeSesk7RruyrczVrCwPQqxQqNXfjvXT08Z2FnpIBgN4KhXp5236SO1yBWipYZIU=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-processor-tag
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: cTZkeCgNSBdKGKfNV1v1bZauUKazTaBpZSHlKFojaDqy4IRbr2mlUQPxGgE4MfABomHmUsm1gq1BkINEZYIj67l+7mir7tegGR/16FXRidzNRRpqaVcVNVuLNxwcP31TK6cH/JFGEC212XMhaWj7+w068yj11B2y/C7x8xuJZG+7+wyFBmN7JqMW0ABxlxY60hB19GQOFb6lOeDRWJdF9iwatWQ67BXzAMCCdKMksR43WX0kDNZ6909xHiz8odWcD1qNxdfZqbazpf8bFBu5Xo88vWC17DXWgVPykveQxQexyZ4DJQ8wY++UOCoobpR8jvXkHwf0q4hYERsGO6JpCc0LRk38ggfoyMt1TBvEtU7JQyRz8WvSDNeGBmtqKDpFjxMbHmp96Ypn6//Y4k5KKg/zxhDTrbzkF25LDfGwv1o4T53b2JA5HIZMoniYX6/awRgN7cmIsD4+5pZFt2ysJbNliJYgf6Bh42FMrySx6cgPyIxXQiinzI7dFQdwTN86GHkPr6D0q/ZFTCgrrGWz2o9yniK/ICPB54JAA5Z9qq+D4YPAD0+daegulheiQWpu2/YatuTH359KwQoKjkAg/XmLZh/eG71nKlsN9DwK3bHOmeSesk7RruyrczVrCwPQqxQqNXfjvXT08Z2FnpIBgN4KhXp5236SO1yBWipYZIU=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-processor-tag
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: releases
  api_key:
    secure: jBMUPENzMk/q3gVBSUssEmcJ+lZVbXAm8L5Kl+7lsM6s2bIml+vDzwgxlAwG7grrmj9zoCdpyBD+OgjtG6w8GaXvbxVghoVUpKzetcyisTylXK5H6nsti33r/Oy8OiWH8SPrkf2AJ1sar0qZ1P9Da3Zeq2omBfZmTypHV1V5OId7GZwTlCdF+vyANbt+BrayDoSWEqsYNwmhsPzASeTfCOfIZOovbaVX6vO2C8pM6SNlZTxhr5oANNAeaAZpXfMNE+Mh+rZvkMVAF2RImWc6lPJGA7jVUzeLp0IMd9pknfvclYg8GF0S7kbsG8rMuzDC05/TZqc76GEkqDh04pdGgu24AkxlLgV086WG44oevU520LYG6qYOMr0QenRGY/T7J+p2cw6Iy+xCOr/NSzdoi0FS8C0ztNMKZGEcTQe8e8uCOnJa6LKS7Ah5SMjUrssqNuoykXaZaJYxKDhSXCN+fkw1maeXiRLPzH397WFkxC5tKt8RgXcME1gHvvtv0uvr63KZHlP5b7WvgVwGC3r5MQfEDDF14rgDEtoPkZZfoKglrInVSASG+FXcYu9Bbt51d7nT8Ikz3QTWtfyJxeAr4HsVBEfilD59YGdzCgBedsqaz6vgYW0FHD1KXB4vT3E+aUED4C4kd5ozPEMsJGlcSUcPO0RdmiOyuZQ9vJgXD6Y=
  file:
    - release/snap-plugin-processor-tag_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-processor-tag
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
